### PR TITLE
Unify path globbing & add ttyACM*

### PR DESCRIPTION
**Pull request by AndreRenaud**

### CODE REVIEW

**Comment by akaeba** [comment]
HI Andre, also suitable for me, and the C&P code is removed. I have only a doubt on this:

```c
for (int path = 0; path < sizeof(path_globs) / sizeof(path_globs[0]); path++)
```
This should only work as long all elements have the exact same length, or is there an additional glue?


BR,
Andreas

**Comment by akaeba** [comment]
The mimic for _apple_ and _linux_ should the same, or is there a difference? If not then you can distinguish between both platforms only in the variable _path_globs[]_.

**Comment by AndreRenaud** [comment]
> This should only work as long all elements have the exact same length, or is there an additional glue?

No, it's not working on the length of the strings, it's doing a division of `sizeof([3]char*)` and `sizeof(char *)`,  so getting `3`. This is a fairly standard mechanism in C for getting the length of statically defined arrays. See this example in the Linux kernel code - https://elixir.bootlin.com/linux/latest/source/include/linux/kernel.h#L56

The code for Linux & Macos is the same - just the paths that they search for is different.

**Review by akaeba — APPROVED** [review]
Great work. Thanks for adjusting.

**Pull request merged**
